config/routes.rb
Rails.application.routes.draw do
  # get 'artists/index'
  resources :artists

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :artist
  has_many :songs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
   has_many :albums
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :album
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all
  end

  def show
    @artist = Artist.find(params[:id])
    @albums = Album.where(artist_id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/index.html.erb
<div class="container", style="width:90%; background-color:#A4A4A4; margin-top: 30px; margin-bottom: 30px; padding: 25px; border: 10px double white;">
 <div class="row">
   <% @artists.each do |artist| %>
     <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 foto-artista shadow">
       <div class="card", style="margin: 10px; padding: 10px; border: 2px solid red;">
         <img class="card-img-top" src=<%= artist.image_url %> alt=<%= artist.name %> height="200px">
         <div class="card-body">
           <h4 class="card-title", style="text-align: center;  font-style: italic;"><%= artist.name %></h4>
           <%= link_to  "Detalles", artist_path(artist), class: "btn btn-primary btn-sm btn-block" %>
         </div>
       </div>
     </div>
   <% end %>
 </div>
</div>

app/views/artists/show.html.erb
<div class="container", style="width:100%; background-color:#A4A4A4; margin-top: 30px; margin-bottom: 30px; padding: 25px; border: 10px double white;">
     <div class="row">
       <div class="col-md-9">
         <h1 class="text-center"><%= @artist.name %></h1>
         <h3 class="text-center">Albums (<%= @albums.length %>) </h3>
         <br>
         <div class="row">
           <% @albums.each do |album| %>
             <div class="col-3 foto-artista-show p-3">
               <div class="card", style="background-color:#A4A4A4">
                 <img class="card-img-top" src=<%= album.image_url %> alt=<%= album.name %> >
                 <div class="card-body", style="text-align: center;">
                   <h5 class="card-title"><%= album.name %></h5>
                   <p><%= album.released_at %></p>
                 </div>
               </div>
            </div>
           <% end %>
         </div>
       </div>
       <div class="col-md-3", padding: 0">
           <img class="card-img-top" src=<%= @artist.image_url %> alt=<%= @artist.name %> height="250px">
       </div>
     </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Music</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background-color:black;">

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
      <a class="navbar-brand" href="#">Real Music</a>
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0"  align="center">
        <li class="nav-item active">
          <a class="nav-link" href="#">Artistas</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="#">Mi Musica</a>
        </li>
      </ul>
      <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Mi Cuenta
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
      </li>
    </div>
    </nav>

    <%= yield %>
  </body>
</html>